"""
SCADE-X Case Report Generator
=============================
Generates structured JSON and Markdown forensic case reports.
"""
import json
from pathlib import Path
from typing import Dict, Any

class CaseReportGenerator:
    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
    def _generate_markdown(self, case_id: str, payload: Dict[str, Any]) -> str:
        md = f"""# SCADE-X Forensic Intelligence Report
**Case ID:** `{case_id}`
**Threat Severity:** {payload['threat_severity']}
**Escalation Priority:** {payload['escalation_priority']}
**Date Generated:** SCADE-X Automated XAI Engine

---

## 1. Executive Summary
{payload['forensic_summary']}

**Recommended Action:** {payload['recommended_action']}
**Action Rationale:** {payload['recommended_action_reason']}

## 2. Root Cause Analysis
- **Primary Cause:** {payload['root_cause']}
- **Secondary Causes:** {', '.join(payload['secondary_causes']) if payload['secondary_causes'] else 'None'}
- **Confidence Assessment:** {payload['confidence_reason']}

## 3. Multi-Layer Explainability

### A. Behavioral Intelligence (ASTRA)
> {payload['behavioral_explanation']}

### B. Process Conformance (SCADE)
> {payload['process_explanation']}

### C. Supply Chain Resilience
> {payload['resilience_explanation']}

---
*Note: This report is generated by SCADE-X's Hybrid Risk-Aware Fusion Layer.*
"""
        return md

    def generate_report(self, case_id: str, payload: Dict[str, Any]):
        """Generates both .json and .md files for the given case."""
        # Clean case_id to ensure safe filename
        safe_case_id = str(case_id).replace("/", "_").replace("\\", "_")
        
        json_path = self.output_dir / f"{safe_case_id}.json"
        md_path = self.output_dir / f"{safe_case_id}.md"
        
        # Write JSON
        with open(json_path, 'w') as f:
            json.dump(payload, f, indent=4)
            
        # Write Markdown
        with open(md_path, 'w') as f:
            f.write(self._generate_markdown(case_id, payload))
